# Numpy arrays

In [1]:
# Create 2 new lists height and weight
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

# Import the numpy package as np
import numpy as np

# Create 2 numpy arrays from height and weight
np_height = np.array(height)
np_weight = np.array(weight)

print(np_height)
print(np_weight)

[1.87 1.87 1.82 1.91 1.9  1.85]
[81.65 97.52 95.25 92.98 86.18 88.45]


In [2]:
type(np_height)

numpy.ndarray

In [3]:
# Calculate bmi (body mass index)
bmi = np_weight / np_height ** 2
bmi

array([23.34925219, 27.88755755, 28.75558507, 25.48723993, 23.87257618,
       25.84368152])

### subsetting

In [4]:
# For a boolean response
bmi > 25

# Print only those observations above 25
bmi[bmi > 25]

array([27.88755755, 28.75558507, 25.48723993, 25.84368152])

# Pandas Basics

In [5]:
dict = {"country": ["Brazil", "Russia", "India", "China", "South Africa"],
       "capital": ["Brasilia", "Moscow", "New Dehli", "Beijing", "Pretoria"],
       "area": [8.516, 17.10, 3.286, 9.597, 1.221],
       "population": [200.4, 143.5, 1252, 1357, 52.98] }

import pandas as pd
brics = pd.DataFrame(dict)
brics

country    capital    area  population
0        Brazil   Brasilia   8.516      200.40
1        Russia     Moscow  17.100      143.50
2         India  New Dehli   3.286     1252.00
3         China    Beijing   9.597     1357.00
4  South Africa   Pretoria   1.221       52.98

In [6]:
# Set the index for brics
brics.index = ["BR", "RU", "IN", "CH", "SA"]

# Print out brics with new index values
brics

country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Dehli   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

In [7]:
# Import the cars.csv data: cars
cars = pd.read_csv('car.csv')

cars

car_ID  symboling                   CarName fueltype aspiration  \
0         1          3        alfa-romero giulia      gas        std   
1         2          3       alfa-romero stelvio      gas        std   
2         3          1  alfa-romero Quadrifoglio      gas        std   
3         4          2               audi 100 ls      gas        std   
4         5          2                audi 100ls      gas        std   
..      ...        ...                       ...      ...        ...   
200     201         -1           volvo 145e (sw)      gas        std   
201     202         -1               volvo 144ea      gas      turbo   
202     203         -1               volvo 244dl      gas        std   
203     204         -1                 volvo 246   diesel      turbo   
204     205         -1               volvo 264gl      gas      turbo   

    doornumber      carbody drivewheel enginelocation  wheelbase  ...  \
0          two  convertible        rwd          front       88.6  ...   
1          two  convertible        rwd          front       88.6  ...   
2          two    hatchback        rwd          front       94.5  ...   
3         four        sedan        fwd          front       99.8  ...   
4         four        sedan        4wd          front       99.4  ...   
..         ...          ...        ...            ...        ...  ...   
200       four        sedan        rwd          front      109.1  ...   
201       four        sedan        rwd          front      109.1  ...   
202       four        sedan        rwd          front      109.1  ...   
203       four        sedan        rwd          front      109.1  ...   
204       four        sedan        rwd          front      109.1  ...   

     enginesize  fuelsystem  boreratio  stroke compressionratio horsepower  \
0           130        mpfi       3.47    2.68              9.0        111   
1           130        mpfi       3.47    2.68              9.0        111   
2           152        mpfi       2.68    3.47              9.0        154   
3           109        mpfi       3.19    3.40             10.0        102   
4           136        mpfi       3.19    3.40              8.0        115   
..          ...         ...        ...     ...              ...        ...   
200         141        mpfi       3.78    3.15              9.5        114   
201         141        mpfi       3.78    3.15              8.7        160   
202         173        mpfi       3.58    2.87              8.8        134   
203         145         idi       3.01    3.40             23.0        106   
204         141        mpfi       3.78    3.15              9.5        114   

     peakrpm citympg  highwaympg    price  
0       5000      21          27  13495.0  
1       5000      21          27  16500.0  
2       5000      19          26  16500.0  
3       5500      24          30  13950.0  
4       5500      18          22  17450.0  
..       ...     ...         ...      ...  
200     5400      23          28  16845.0  
201     5300      19          25  19045.0  
202     5500      18          23  21485.0  
203     4800      26          27  22470.0  
204     5400      19          25  22625.0  

[205 rows x 26 columns]

### Indexing Dataframes

In [8]:
cars = pd.read_csv('car.csv', index_col = 0)

# Print out country column as Pandas Series
print(cars['CarName'])

# Print out country column as Pandas DataFrame
print(cars[['CarName']])

# Print out DataFrame with country and drives_right columns
print(cars[['CarName', 'carbody']])

car_ID
1            alfa-romero giulia
2           alfa-romero stelvio
3      alfa-romero Quadrifoglio
4                   audi 100 ls
5                    audi 100ls
                 ...           
201             volvo 145e (sw)
202                 volvo 144ea
203                 volvo 244dl
204                   volvo 246
205                 volvo 264gl
Name: CarName, Length: 205, dtype: object
                         CarName
car_ID                          
1             alfa-romero giulia
2            alfa-romero stelvio
3       alfa-romero Quadrifoglio
4                    audi 100 ls
5                     audi 100ls
...                          ...
201              volvo 145e (sw)
202                  volvo 144ea
203                  volvo 244dl
204                    volvo 246
205                  volvo 264gl

[205 rows x 1 columns]
                         CarName      carbody
car_ID                                       
1             alfa-romero giulia  convertible
2       

In [9]:
cars = pd.read_csv('car.csv', index_col = 0)

# Print out first 4 observations
print(cars[0:4])

# Print out fifth and sixth observation
print(cars[4:6])

        symboling                   CarName fueltype aspiration doornumber  \
car_ID                                                                       
1               3        alfa-romero giulia      gas        std        two   
2               3       alfa-romero stelvio      gas        std        two   
3               1  alfa-romero Quadrifoglio      gas        std        two   
4               2               audi 100 ls      gas        std       four   

            carbody drivewheel enginelocation  wheelbase  carlength  ...  \
car_ID                                                               ...   
1       convertible        rwd          front       88.6      168.8  ...   
2       convertible        rwd          front       88.6      168.8  ...   
3         hatchback        rwd          front       94.5      171.2  ...   
4             sedan        fwd          front       99.8      176.6  ...   

        enginesize  fuelsystem  boreratio stroke compressionratio  horsepo

In [10]:
cars = pd.read_csv('car.csv', index_col = 0)

# Print out observation for Japan
print(cars.iloc[2])

symboling                                  1
CarName             alfa-romero Quadrifoglio
fueltype                                 gas
aspiration                               std
doornumber                               two
carbody                            hatchback
drivewheel                               rwd
enginelocation                         front
wheelbase                               94.5
carlength                              171.2
carwidth                                65.5
carheight                               52.4
curbweight                              2823
enginetype                              ohcv
cylindernumber                           six
enginesize                               152
fuelsystem                              mpfi
boreratio                               2.68
stroke                                  3.47
compressionratio                           9
horsepower                               154
peakrpm                                 5000
citympg   

In [11]:
# Print out observations
print(cars.loc[1])

symboling                            3
CarName             alfa-romero giulia
fueltype                           gas
aspiration                         std
doornumber                         two
carbody                    convertible
drivewheel                         rwd
enginelocation                   front
wheelbase                         88.6
carlength                        168.8
carwidth                          64.1
carheight                         48.8
curbweight                        2548
enginetype                        dohc
cylindernumber                    four
enginesize                         130
fuelsystem                        mpfi
boreratio                         3.47
stroke                            2.68
compressionratio                     9
horsepower                         111
peakrpm                           5000
citympg                             21
highwaympg                          27
price                            13495
Name: 1, dtype: object
