**Why to use Numpy instead of list ??**

* List is slow than numpy
* Numpy uses relatively less memory to store data than list
* We can do many operation with numpy than list

In [1]:
import numpy as np

## one dimensional array

In [2]:
a = np.array([5,7,3])
a

array([5, 7, 3])

In [3]:
a = np.array([5,7,3])
print(a)

[5 7 3]


In [6]:
a = np.array([5,7,3], dtype="float")
print(a)

[5. 7. 3.]


## two dimensional array

In [7]:
a = np.array([[5,7,3],[6,8,9]])
print(a)

[[5 7 3]
 [6 8 9]]


In [8]:
a.ndim

2

In [9]:
a.shape

(2, 3)

In [10]:
a.dtype

dtype('int32')

In [11]:
a.size

6

In [12]:
a[1,1] # 1th row and 1th column

8

In [13]:
a[0,:] # 0th row and all column

array([5, 7, 3])

In [14]:
a[:,1] # all row and 1th column

array([7, 8])

In [15]:
# we can also change the element of array
a[1,1]=16

In [16]:
a

array([[ 5,  7,  3],
       [ 6, 16,  9]])

## 3 dimensional array

In [17]:
a = np.array([[[5,7,3],[6,8,9]],[[7,9,0],[8,5,6]]])
print(a)

[[[5 7 3]
  [6 8 9]]

 [[7 9 0]
  [8 5 6]]]


In [18]:
a[1,0,2]

0

# Types of matrix

***zero matrix***

In [21]:
z = np.zeros((3,3),dtype='int32')
z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

***ones matrix***

In [22]:
o = np.ones((4,4))
o

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

***Identity matrix***

In [37]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## full and full_like

In [25]:
np.full((4,4),6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [26]:
np.full_like(o,2)

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [27]:
np.full_like(z,10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

## Random decimal number

In [32]:
np.random.rand(3,2)

array([[0.1305435 , 0.03941858],
       [0.17463083, 0.40877144],
       [0.30370952, 0.24757324]])

## Random integer number

In [36]:
np.random.randint(1,10,(4,4))

array([[2, 5, 9, 2],
       [6, 8, 3, 6],
       [6, 3, 8, 3],
       [2, 2, 2, 6]])

## copy an array

In [39]:
o = np.ones((4,4))
d=o.copy()
print(d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Arithmetic operation with numpy

In [47]:
a = np.array([2,1,4,5])
print(a)

[2 1 4 5]


In [48]:
a+2

array([4, 3, 6, 7])

In [49]:
a-1

array([1, 0, 3, 4])

In [50]:
a*2

array([ 4,  2,  8, 10])

In [51]:
a/2

array([1. , 0.5, 2. , 2.5])

In [52]:
a**2

array([ 4,  1, 16, 25], dtype=int32)

In [53]:
a%2

array([0, 1, 0, 1], dtype=int32)

In [55]:
b = np.array([4,7,5,6])
print(b)

[4 7 5 6]


In [56]:
a+b

array([ 6,  8,  9, 11])

In [57]:
np.sin(a)

array([ 0.90929743,  0.84147098, -0.7568025 , -0.95892427])

In [58]:
np.cos(a)

array([-0.41614684,  0.54030231, -0.65364362,  0.28366219])

## Linear algebra

In [69]:
a=np.ones((2,3), dtype='int16')
print(a)

b=np.zeros((3,1), dtype='int16')+2
print(b)

np.matmul(a,b)

[[1 1 1]
 [1 1 1]]
[[2]
 [2]
 [2]]


array([[6],
       [6]], dtype=int16)

In [107]:
# Determinant
a = np.identity(2, dtype='int8')+2
print(a)
np.linalg.det(a).round()

[[3 2]
 [2 3]]


5.0

In [86]:
a = np.array([[1,3,6,8],[3,7,10,15]])
print(a)
np.min(a)

[[ 1  3  6  8]
 [ 3  7 10 15]]


1

In [87]:
np.max(a)

15

In [88]:
np.min(a,axis=0)

array([1, 3, 6, 8])

In [90]:
np.max(a,axis=1)

array([ 8, 15])

In [93]:
np.sum(a)

53

## reshape method

In [101]:
a= np.array([1,2,3,4,5,6,7,8,9,10])
print(a)
a.reshape(2,5)

[ 1  2  3  4  5  6  7  8  9 10]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## How can we load data from files

In [104]:
# file = np.genfromtxt('text.txt', delimiter=',')
# file.astype('int16')

## Solve the equation

In [105]:
# 2 * a + b = 6 and a + 2 * b = 3

#ans: a=3 and b=0

x = np.array([[2,1],[1,2]])
y = np.array([6,3])
result = np.linalg.solve(x,y)
result

array([3., 0.])